---
abstract: 'Test::Deep extension to check predicates on plain scalars'
author:
  - 'Andrei Mischhcenko <me@druxa.ru>'
build_requires:
  Test::More: 0
  Test::Tester: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Deep-This
requires:
  Data::Dumper: 0
  Exporter: 0
  Test::Deep: 0
  Test::Deep::Cmp: 0
  overload: 0
resources:
  bugtracker: http://github.com/druxa/test_deep_this/issues
  homepage: http://github.com/druxa/test_deep_this/
  repository: git://github.com/druxa/test_deep_this.git
version: 1.00
